// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyvutgdomhifdrepnigb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dnV0Z2RvbWhpZmRyZXBuaWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTc3NDMsImV4cCI6MjA2MzQ3Mzc0M30.lZSy-CX3oVNFnWtzgymXHU3eSUV1danTAer301oZtZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);